open! Bonsai_web

(** Scoped ppx_css classes (see style.ml). Only the accessors referenced by the
    view are exposed; each is a [Vdom.Attr.t] carrying the hashed class name. *)

val achievement : Vdom.Attr.t
val action : Vdom.Attr.t
val action_title : Vdom.Attr.t
val actions : Vdom.Attr.t
val alert_error : Vdom.Attr.t
val app : Vdom.Attr.t
val between : Vdom.Attr.t
val bg_fail : Vdom.Attr.t
val bg_pending : Vdom.Attr.t
val bg_success : Vdom.Attr.t
val bottom_sheet_overlay : Vdom.Attr.t
val btn : Vdom.Attr.t
val caption : Vdom.Attr.t
val card : Vdom.Attr.t
val card_text : Vdom.Attr.t
val card_title : Vdom.Attr.t
val center : Vdom.Attr.t
val center_v : Vdom.Attr.t
val checkbox_row : Vdom.Attr.t
val col : Vdom.Attr.t
val col6 : Vdom.Attr.t
val container : Vdom.Attr.t
val endgame_message : Vdom.Attr.t
val endgame_table_wrap : Vdom.Attr.t
val endgame_title : Vdom.Attr.t
val field_error : Vdom.Attr.t
val fill : Vdom.Attr.t
val fullscreen : Vdom.Attr.t
val fw : Vdom.Attr.t
val ga_2 : Vdom.Attr.t
val game_board : Vdom.Attr.t
val game_section : Vdom.Attr.t
val icon_btn : Vdom.Attr.t
val info_card : Vdom.Attr.t
val label : Vdom.Attr.t
val layers_text : Vdom.Attr.t
val li_append : Vdom.Attr.t
val li_mid : Vdom.Attr.t
val li_prepend : Vdom.Attr.t
val li_title : Vdom.Attr.t
val lobby_buttons : Vdom.Attr.t
val lobby_inner : Vdom.Attr.t
val lobby_select : Vdom.Attr.t
val login_form : Vdom.Attr.t
val mission_panel : Vdom.Attr.t
val mission_result : Vdom.Attr.t
val mt_4 : Vdom.Attr.t
val mt_6 : Vdom.Attr.t
val outlined : Vdom.Attr.t
val overlay : Vdom.Attr.t
val overlay_card : Vdom.Attr.t
val pa_4 : Vdom.Attr.t
val player_name : Vdom.Attr.t
val primary : Vdom.Attr.t
val pt_2 : Vdom.Attr.t
val pt_6 : Vdom.Attr.t
val pt_8 : Vdom.Attr.t
val role_cell : Vdom.Attr.t
val row : Vdom.Attr.t
val sheet : Vdom.Attr.t
val spacer : Vdom.Attr.t
val spinner : Vdom.Attr.t
val spinner_lg : Vdom.Attr.t
val start : Vdom.Attr.t
val stats_header : Vdom.Attr.t
val stats_wrap : Vdom.Attr.t
val subtitle : Vdom.Attr.t
val summary_table : Vdom.Attr.t
val tab : Vdom.Attr.t
val tab_active : Vdom.Attr.t
val tab_mission : Vdom.Attr.t
val tabs : Vdom.Attr.t
val text_field : Vdom.Attr.t
val text_h4 : Vdom.Attr.t
val text_h5 : Vdom.Attr.t
val text_h6 : Vdom.Attr.t
val thin : Vdom.Attr.t
val title_bar : Vdom.Attr.t
val toolbar : Vdom.Attr.t
val toolbar_email : Vdom.Attr.t
val upper : Vdom.Attr.t
val welcome : Vdom.Attr.t
val welcome_heading : Vdom.Attr.t
val wrap : Vdom.Attr.t
